---
name: Build Project
on:
  push:
    tags: v**

jobs:
  build:
    name: Build Vigenere executable
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        include:
          - os: ubuntu-22.04
            arch: x86_64-linux
          - os: macos-14
            arch: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Binary
        run: nix build
      - uses: actions/upload-artifact@v4
        with:
          name: vigenere-${{ matrix.arch }}
          path: result/bin/vigenere
  release:
    name: Create and Publish Release
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: vigenere-**/vigenere
