---
name: Build Project
on:
  push:
    tags: v**

jobs:
  build:
    name: Build Vigenere executable
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        include:
          - os: ubuntu-22.04
            arch: x86_64-linux
          - os: macos-14
            arch: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: spyicydev
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Binary
        run: nix build
      - name: Create zip
        run: zip vigenere-${{ matrix.arch }}.zip result/bin/vigenere
      - uses: actions/upload-artifact@v4
        with:
          name: vigenere-${{ matrix.arch }}
          path: vigenere-${{ matrix.arch }}.zip

  release:
    name: Create and Publish Release
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          artifacts: vigenere-*/vigenere-*.zip
